# Generated by Django 4.2.11 on 2024-03-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionUsuarioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.user')),
            ],
        ),
    ]
