# Generated by Django 4.2.11 on 2024-03-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_sala_latitud_sala_longitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividades',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='carrera',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='edificio',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='facultad',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='Semestre',
            new_name='semestre',
        ),
        migrations.RenameField(
            model_name='planta',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='Descripcion',
            new_name='descripcion',
        ),
    ]
