# Generated by Django 4.2.11 on 2024-03-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0005_relacionmateriasala'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='relacionmateriasala',
            name='dia_semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.diassemana'),
        ),
    ]
