# Generated by Django 4.2.11 on 2024-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0006_diassemana_alter_relacionmateriasala_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionmateriasala',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
